# Generated by Django 6.0.4 on 2026-05-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculties', models.ManyToManyField(blank=True, related_name='tutors', to='students.faculty', verbose_name='Fakultetlar')),
                ('groups', models.ManyToManyField(blank=True, related_name='tutors', to='students.group', verbose_name='Guruhlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tyutor profili',
                'verbose_name_plural': 'Tyutorlar profillari',
            },
        ),
    ]
