# Generated by Django 6.0.4 on 2026-05-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Fakultet nomi')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Qisqa nomi')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Hudud nomi')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Guruh nomi')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Kurs')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='students.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['faculty__name', 'name'],
                'unique_together': {('faculty', 'name')},
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tuman nomi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='students.region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['region__name', 'name'],
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default='Toshkent davlat universiteti', max_length=200, verbose_name="Oliy ta'lim muassasasi")),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Kurs')),
                ('housing_type', models.CharField(choices=[('rent', 'Ijarada'), ('dormitory', 'Yotoqxonada'), ('home', "O'z uyida")], default='home', max_length=16, verbose_name='Yashash turi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('passport', models.CharField(blank=True, max_length=20, verbose_name='Pasport seriyasi')),
                ('profile_completed', models.BooleanField(default=False, verbose_name="Profil to'ldirilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.faculty', verbose_name='Fakultet')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.group', verbose_name='Guruh')),
                ('home_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_students', to='students.district', verbose_name="Tug'ilgan tuman")),
                ('home_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_students', to='students.region', verbose_name="Tug'ilgan hudud")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Talaba profili',
                'verbose_name_plural': 'Talabalar profillari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik ijara narxi (so'm)")),
                ('owner_full_name', models.CharField(max_length=120, verbose_name='Uy egasining F.I.Sh')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Uy egasi telefoni')),
                ('owner_passport', models.CharField(blank=True, max_length=20, verbose_name='Uy egasi pasporti')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'lov qilingan")),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name="Oxirgi to'lov sanasi")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='students.district', verbose_name='Tuman')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='students.region', verbose_name='Hudud')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='students.studentprofile', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Ijara ma'lumoti",
                'verbose_name_plural': "Ijara ma'lumotlari",
            },
        ),
    ]
